import {
  IoLayersOutline,
  IoColorPaletteOutline,
  IoFlashOutline,
  IoDiamondOutline,
  IoGlobeOutline,
  IoShieldCheckmarkOutline,
  IoRocketOutline,
  IoBusinessOutline,
  IoBriefcaseOutline,
  IoStatsChartOutline,
  IoHardwareChipOutline,
  IoCubeOutline,
  IoGitNetworkOutline,
  IoSparklesOutline,
  IoInfiniteOutline,
  IoFingerPrintOutline,
  IoAnalyticsOutline,
  IoCheckmarkCircleSharp,
  IoCartOutline,
  IoPeopleOutline,
  IoBagCheckOutline,
  IoCardOutline,
  IoSyncOutline,
  IoStorefrontOutline,
  IoSettingsOutline,
  IoCodeSlashOutline,
  IoCloudUploadOutline,
  IoTimeOutline,
  IoReaderOutline,
  IoImagesOutline,
  IoShareSocialOutline,
  IoShapesOutline,
  IoTrendingUpOutline,
  IoSearchOutline,
  IoFilmOutline,
  IoPulseOutline,
  IoBarChartOutline,
  IoFilterOutline,
  IoBugOutline,
  IoFlaskOutline,
  IoColorWandOutline,
  IoChatbubblesOutline,
  IoExtensionPuzzleOutline,
  IoServerOutline,
  IoConstructOutline,
  IoSchoolOutline,
  IoPersonAddOutline,
  IoCalculatorOutline,
  IoMegaphoneOutline,
  IoHammerOutline,
  IoHeadsetOutline,
  IoCloudDownloadOutline,
  IoTerminalOutline,
  IoShieldCheckmark
} from "react-icons/io5";

const iconMap = {
  Layers: IoLayersOutline,
  Palette: IoColorPaletteOutline,
  ColorPalette: IoColorPaletteOutline,
  Flash: IoFlashOutline,
  Diamond: IoDiamondOutline,
  Globe: IoGlobeOutline,
  Shield: IoShieldCheckmarkOutline,
  ShieldCheckmark: IoShieldCheckmarkOutline,
  Rocket: IoRocketOutline,
  Business: IoBusinessOutline,
  Briefcase: IoBriefcaseOutline,
  Stats: IoStatsChartOutline,
  Chip: IoHardwareChipOutline,
  Cube: IoCubeOutline,
  GitNetwork: IoGitNetworkOutline,
  Sparkles: IoSparklesOutline,
  Infinite: IoInfiniteOutline,
  FingerPrint: IoFingerPrintOutline,
  Analytics: IoAnalyticsOutline,
  Checkmark: IoCheckmarkCircleSharp,
  Cart: IoCartOutline,
  People: IoPeopleOutline,
  BagCheck: IoBagCheckOutline,
  Card: IoCardOutline,
  Sync: IoSyncOutline,
  Storefront: IoStorefrontOutline,
  Settings: IoSettingsOutline,
  Code: IoCodeSlashOutline,
  Terminal: IoTerminalOutline,
  CloudUpload: IoCloudUploadOutline,
  Time: IoTimeOutline,
  Reader: IoReaderOutline,
  Images: IoImagesOutline,
  ShareSocial: IoShareSocialOutline,
  Shapes: IoShapesOutline,
  TrendingUp: IoTrendingUpOutline,
  Search: IoSearchOutline,
  Film: IoFilmOutline,
  Pulse: IoPulseOutline,
  BarChart: IoBarChartOutline,
  Filter: IoFilterOutline,
  Bug: IoBugOutline,
  Flask: IoFlaskOutline,
  ColorWand: IoColorWandOutline,
  Chatbubbles: IoChatbubblesOutline,
  Puzzle: IoExtensionPuzzleOutline,
  Server: IoServerOutline,
  Construct: IoConstructOutline,
  School: IoSchoolOutline,
  PersonAdd: IoPersonAddOutline,
  Calculator: IoCalculatorOutline,
  Megaphone: IoMegaphoneOutline,
  Hammer: IoHammerOutline,
  Headset: IoHeadsetOutline,
  CloudDownload: IoCloudDownloadOutline
};

export const getIcon = (name, props = {}) => {
  const Icon = iconMap[name] || IoCubeOutline;
  return <Icon {...props} />;
};
